name: finance_pg
channels:
  - default
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - python=3.7.6
  - pip=20.0.2
  - matplotlib=3.2.1
  - pip:
    - pandas==1.0.3
    - numpy==1.18.3
    - scikit-learn==0.22.2.post1
    - xlrd==1.2.0
    - openpyxl==3.0.3
    - lightgbm==2.3.1
    - ipython==7.13.0
    - seaborn==0.10.0
    - pyyaml==5.3.1
    - ipykernel==5.2.1
    - statsmodels==0.11.1
    - python-box==4.2.3
    - sphinx==1.8.*
    - jupyter==1.0.0
    - gcsfs==0.6.2
    - yfinance==0.1.54
