###########################################################################
# Default configuration parameters for downloading data
###########################################################################

